sudo: false
script: "bundle exec rake neo4j:install['enterprise','2.0.1'] neo4j:get_spatial neo4j:start knapsack:rspec --trace"
language: ruby
rvm:
  - 2.0.0
env:
  global:
    - CI_NODE_TOTAL=3
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
